version: '3.9'

services:
  backend:
    build:
      context: ./app
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
